[package]
name = "advent-of-code-2022"
# don't change this, it's updated before an actual build by update-version.sh
version = "0.0.0-development"
edition = "2021"
rust-version = "1.65.0"
authors = ["Kristof Mattei"]
license-file = "LICENSE"
description = "Advent of Code 2022"
repository = "https://github.com/kristof-mattei/advent-of-code-2022"
keywords = ["playground"]
categories = ["playground"]

[profile.dev]
debug = true

[profile.release]
debug = true

[profile.bench]
debug = true

[profile.test]
debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
coverage = []

[dependencies]
# regex = "1"


# We compile the Docker container with musl to get a static library. Smaller, faster.
# BUT that means that we need to include openssl
# Documentation on the syntax:
# https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies
[target.'cfg(all(target_arch = "x86_64", target_os="linux", target_env="musl"))'.dependencies]
# openssl = { version = "0.10.36", features = ["vendored"] }
